State: 1
Info: ''
Logo: pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Grass.png
ReleaseTime: 2025-03-25 20:14
VersionFabric: ''
VersionLegacyFabric: ''
VersionQuilt: ''
VersionLabyMod: ''
VersionOptiFine: ''
VersionLiteLoader: false
VersionForge: ''
VersionNeoForge: ''
VersionCleanroom: ''
VersionApiCode: -1
VersionOriginal: 1.21.5
VersionOriginalMain: 21
VersionOriginalSub: 5
